# CMake generated Testfile for 
# Source directory: /home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test
# Build directory: /home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_sanity "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_sanity")
set_tests_properties(test_sanity PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;74;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_signal_gen "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_signal_gen")
set_tests_properties(test_signal_gen PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;80;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_tone "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_tone")
set_tests_properties(test_tone PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;93;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_pcm_ring "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_pcm_ring")
set_tests_properties(test_pcm_ring PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;99;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_i2s_out_pump "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_i2s_out_pump")
set_tests_properties(test_i2s_out_pump PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;106;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_i2s_out_gain "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_i2s_out_gain")
set_tests_properties(test_i2s_out_gain PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;112;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_bt_link_parser "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_bt_link_parser")
set_tests_properties(test_bt_link_parser PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;118;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_bt_link_session "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_bt_link_session")
set_tests_properties(test_bt_link_session PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;125;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_wifi_sm "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_wifi_sm")
set_tests_properties(test_wifi_sm PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;131;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_radio_parse "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_radio_parse")
set_tests_properties(test_radio_parse PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;137;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_station_store "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_station_store")
set_tests_properties(test_station_store PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;143;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_radio_resampler "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_radio_resampler")
set_tests_properties(test_radio_resampler PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;149;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_ctrl_cfg "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_ctrl_cfg")
set_tests_properties(test_ctrl_cfg PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;157;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_ctrl_sm "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_ctrl_sm")
set_tests_properties(test_ctrl_sm PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;163;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_radio_lifecycle "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_radio_lifecycle")
set_tests_properties(test_radio_lifecycle PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;183;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_pack_s16_msb "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_pack_s16_msb")
set_tests_properties(test_pack_s16_msb PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;188;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_bt_link_lifecycle "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_bt_link_lifecycle")
set_tests_properties(test_bt_link_lifecycle PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;208;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_ctrl_init "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_ctrl_init")
set_tests_properties(test_ctrl_init PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;227;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
add_test(test_main_boot "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/test_main_boot")
set_tests_properties(test_main_boot PROPERTIES  _BACKTRACE_TRIPLES "/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;254;add_test;/home/phil/work/esp32_btaudio/esp_i2s_source/test/host_test/CMakeLists.txt;0;")
